"""project description, customer code, bom version metadata

Revision ID: 6d1643ceb5ac
Revises: 8e5da27ca791
Create Date: 2026-06-15 14:37:16.255225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1643ceb5ac'
down_revision: Union[str, None] = '8e5da27ca791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_versions', sa.Column('version_name', sa.String(length=80), nullable=True))
    op.add_column('bom_versions', sa.Column('revision_code', sa.String(length=40), nullable=True))
    op.add_column('bom_versions', sa.Column('source_file_name', sa.String(length=255), nullable=True))
    op.add_column('bom_versions', sa.Column('source_doc_number', sa.String(length=120), nullable=True))
    op.add_column('bom_versions', sa.Column('board_name', sa.String(length=160), nullable=True))
    op.add_column('bom_versions', sa.Column('revised_date', sa.String(length=40), nullable=True))
    op.add_column('bom_versions', sa.Column('bom_type', sa.String(length=40), nullable=True))
    op.add_column('bom_versions', sa.Column('build_quantity', sa.Integer(), nullable=True))
    op.add_column('bom_versions', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bom_versions', sa.Column('imported_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('bom_versions', 'version_label',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_foreign_key(None, 'bom_versions', 'users', ['imported_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('customers', sa.Column('code', sa.String(length=40), nullable=True))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    op.drop_column('customers', 'code')
    op.drop_constraint(None, 'bom_versions', type_='foreignkey')
    op.alter_column('bom_versions', 'version_label',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('bom_versions', 'imported_by_user_id')
    op.drop_column('bom_versions', 'imported_at')
    op.drop_column('bom_versions', 'build_quantity')
    op.drop_column('bom_versions', 'bom_type')
    op.drop_column('bom_versions', 'revised_date')
    op.drop_column('bom_versions', 'board_name')
    op.drop_column('bom_versions', 'source_doc_number')
    op.drop_column('bom_versions', 'source_file_name')
    op.drop_column('bom_versions', 'revision_code')
    op.drop_column('bom_versions', 'version_name')
    # ### end Alembic commands ###
