"""project soft delete

Revision ID: 8e5da27ca791
Revises: 8f35c4ab0011
Create Date: 2026-06-15 13:47:41.816285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5da27ca791'
down_revision: Union[str, None] = '8f35c4ab0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
