"""bom_line pcb fields

Revision ID: 8f35c4ab0011
Revises: f49e1b01bae8
Create Date: 2026-06-15 13:13:52.452371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f35c4ab0011'
down_revision: Union[str, None] = 'f49e1b01bae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_lines', sa.Column('footprint', sa.String(length=120), nullable=True))
    op.add_column('bom_lines', sa.Column('value', sa.String(length=120), nullable=True))
    op.add_column('bom_lines', sa.Column('supplier_part_number', sa.String(length=120), nullable=True))
    op.add_column('bom_lines', sa.Column('dnp', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_lines', 'dnp')
    op.drop_column('bom_lines', 'supplier_part_number')
    op.drop_column('bom_lines', 'value')
    op.drop_column('bom_lines', 'footprint')
    # ### end Alembic commands ###
