"""bom quality, china quote, pricing fields

Revision ID: c113a98924db
Revises: 6d1643ceb5ac
Create Date: 2026-06-15 15:23:05.680124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c113a98924db'
down_revision: Union[str, None] = '6d1643ceb5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_lines', sa.Column('cleaned_mpn', sa.String(length=120), nullable=True))
    op.add_column('bom_lines', sa.Column('required_qty', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('bom_lines', sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('bom_lines', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('bom_lines', sa.Column('quality_status', sa.String(length=20), server_default='ok', nullable=False))
    op.add_column('bom_lines', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bom_lines', sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True))
    op.add_column('bom_lines', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'bom_lines', 'users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('pricing_lines', sa.Column('source_quote_line_id', sa.Integer(), nullable=True))
    op.add_column('pricing_lines', sa.Column('selected_source', sa.String(length=40), nullable=True))
    op.add_column('pricing_lines', sa.Column('required_qty', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('pricing_lines', sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('pricing_lines', sa.Column('extended_cost', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('pricing_lines', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('pricing_lines', sa.Column('match_confidence', sa.Integer(), nullable=True))
    op.add_column('pricing_lines', sa.Column('pricing_status', sa.String(length=20), server_default='missing_price', nullable=False))
    op.add_column('pricing_lines', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'pricing_lines', 'supplier_quote_lines', ['source_quote_line_id'], ['id'], ondelete='SET NULL')
    op.add_column('pricing_snapshots', sa.Column('snapshot_name', sa.String(length=160), nullable=True))
    op.add_column('pricing_snapshots', sa.Column('source_type', sa.String(length=40), server_default='china_quote', nullable=False))
    op.add_column('pricing_snapshots', sa.Column('supplier_quote_id', sa.Integer(), nullable=True))
    op.add_column('pricing_snapshots', sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False))
    op.add_column('pricing_snapshots', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pricing_snapshots', 'supplier_quotes', ['supplier_quote_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pricing_snapshots', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('supplier_quote_lines', sa.Column('line_number', sa.Integer(), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('quoted_mpn', sa.String(length=120), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('cleaned_quoted_mpn', sa.String(length=120), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('supplier_part_number', sa.String(length=120), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('lead_time', sa.String(length=40), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('available_qty', sa.Integer(), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('matched_bom_line_id', sa.Integer(), nullable=True))
    op.add_column('supplier_quote_lines', sa.Column('match_status', sa.String(length=20), server_default='not_matched', nullable=False))
    op.add_column('supplier_quote_lines', sa.Column('match_confidence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('supplier_quote_lines', sa.Column('match_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'supplier_quote_lines', 'bom_lines', ['matched_bom_line_id'], ['id'], ondelete='SET NULL')
    op.add_column('supplier_quotes', sa.Column('bom_version_id', sa.Integer(), nullable=True))
    op.add_column('supplier_quotes', sa.Column('quote_name', sa.String(length=160), nullable=True))
    op.add_column('supplier_quotes', sa.Column('source_type', sa.String(length=40), server_default='china', nullable=False))
    op.add_column('supplier_quotes', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('supplier_quotes', sa.Column('source_file_name', sa.String(length=255), nullable=True))
    op.add_column('supplier_quotes', sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
    op.add_column('supplier_quotes', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'supplier_quotes', 'bom_versions', ['bom_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'supplier_quotes', 'users', ['uploaded_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_quotes', type_='foreignkey')
    op.drop_constraint(None, 'supplier_quotes', type_='foreignkey')
    op.drop_column('supplier_quotes', 'uploaded_at')
    op.drop_column('supplier_quotes', 'uploaded_by_user_id')
    op.drop_column('supplier_quotes', 'source_file_name')
    op.drop_column('supplier_quotes', 'valid_until')
    op.drop_column('supplier_quotes', 'source_type')
    op.drop_column('supplier_quotes', 'quote_name')
    op.drop_column('supplier_quotes', 'bom_version_id')
    op.drop_constraint(None, 'supplier_quote_lines', type_='foreignkey')
    op.drop_column('supplier_quote_lines', 'match_reason')
    op.drop_column('supplier_quote_lines', 'match_confidence')
    op.drop_column('supplier_quote_lines', 'match_status')
    op.drop_column('supplier_quote_lines', 'matched_bom_line_id')
    op.drop_column('supplier_quote_lines', 'available_qty')
    op.drop_column('supplier_quote_lines', 'lead_time')
    op.drop_column('supplier_quote_lines', 'supplier_part_number')
    op.drop_column('supplier_quote_lines', 'cleaned_quoted_mpn')
    op.drop_column('supplier_quote_lines', 'quoted_mpn')
    op.drop_column('supplier_quote_lines', 'line_number')
    op.drop_constraint(None, 'pricing_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'pricing_snapshots', type_='foreignkey')
    op.drop_column('pricing_snapshots', 'created_by_user_id')
    op.drop_column('pricing_snapshots', 'currency')
    op.drop_column('pricing_snapshots', 'supplier_quote_id')
    op.drop_column('pricing_snapshots', 'source_type')
    op.drop_column('pricing_snapshots', 'snapshot_name')
    op.drop_constraint(None, 'pricing_lines', type_='foreignkey')
    op.drop_column('pricing_lines', 'notes')
    op.drop_column('pricing_lines', 'pricing_status')
    op.drop_column('pricing_lines', 'match_confidence')
    op.drop_column('pricing_lines', 'currency')
    op.drop_column('pricing_lines', 'extended_cost')
    op.drop_column('pricing_lines', 'unit_cost')
    op.drop_column('pricing_lines', 'required_qty')
    op.drop_column('pricing_lines', 'selected_source')
    op.drop_column('pricing_lines', 'source_quote_line_id')
    op.drop_constraint(None, 'bom_lines', type_='foreignkey')
    op.drop_column('bom_lines', 'updated_at')
    op.drop_column('bom_lines', 'reviewed_by_user_id')
    op.drop_column('bom_lines', 'reviewed_at')
    op.drop_column('bom_lines', 'quality_status')
    op.drop_column('bom_lines', 'review_reason')
    op.drop_column('bom_lines', 'needs_review')
    op.drop_column('bom_lines', 'required_qty')
    op.drop_column('bom_lines', 'cleaned_mpn')
    # ### end Alembic commands ###
