/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as UploadBomRouteImport } from './routes/upload-bom'
import { Route as RepQuoteRouteImport } from './routes/rep-quote'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ChinaQuoteRouteImport } from './routes/china-quote'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as BomRouteImport } from './routes/bom'
import { Route as IndexRouteImport } from './routes/index'

const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadBomRoute = UploadBomRouteImport.update({
  id: '/upload-bom',
  path: '/upload-bom',
  getParentRoute: () => rootRouteImport,
} as any)
const RepQuoteRoute = RepQuoteRouteImport.update({
  id: '/rep-quote',
  path: '/rep-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinaQuoteRoute = ChinaQuoteRouteImport.update({
  id: '/china-quote',
  path: '/china-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/changes': typeof ChangesRoute
  '/china-quote': typeof ChinaQuoteRoute
  '/project': typeof ProjectRoute
  '/quality': typeof QualityRoute
  '/rep-quote': typeof RepQuoteRoute
  '/upload-bom': typeof UploadBomRoute
  '/versions': typeof VersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/changes': typeof ChangesRoute
  '/china-quote': typeof ChinaQuoteRoute
  '/project': typeof ProjectRoute
  '/quality': typeof QualityRoute
  '/rep-quote': typeof RepQuoteRoute
  '/upload-bom': typeof UploadBomRoute
  '/versions': typeof VersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/changes': typeof ChangesRoute
  '/china-quote': typeof ChinaQuoteRoute
  '/project': typeof ProjectRoute
  '/quality': typeof QualityRoute
  '/rep-quote': typeof RepQuoteRoute
  '/upload-bom': typeof UploadBomRoute
  '/versions': typeof VersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bom'
    | '/changes'
    | '/china-quote'
    | '/project'
    | '/quality'
    | '/rep-quote'
    | '/upload-bom'
    | '/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bom'
    | '/changes'
    | '/china-quote'
    | '/project'
    | '/quality'
    | '/rep-quote'
    | '/upload-bom'
    | '/versions'
  id:
    | '__root__'
    | '/'
    | '/bom'
    | '/changes'
    | '/china-quote'
    | '/project'
    | '/quality'
    | '/rep-quote'
    | '/upload-bom'
    | '/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BomRoute: typeof BomRoute
  ChangesRoute: typeof ChangesRoute
  ChinaQuoteRoute: typeof ChinaQuoteRoute
  ProjectRoute: typeof ProjectRoute
  QualityRoute: typeof QualityRoute
  RepQuoteRoute: typeof RepQuoteRoute
  UploadBomRoute: typeof UploadBomRoute
  VersionsRoute: typeof VersionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-bom': {
      id: '/upload-bom'
      path: '/upload-bom'
      fullPath: '/upload-bom'
      preLoaderRoute: typeof UploadBomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rep-quote': {
      id: '/rep-quote'
      path: '/rep-quote'
      fullPath: '/rep-quote'
      preLoaderRoute: typeof RepQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/china-quote': {
      id: '/china-quote'
      path: '/china-quote'
      fullPath: '/china-quote'
      preLoaderRoute: typeof ChinaQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BomRoute: BomRoute,
  ChangesRoute: ChangesRoute,
  ChinaQuoteRoute: ChinaQuoteRoute,
  ProjectRoute: ProjectRoute,
  QualityRoute: QualityRoute,
  RepQuoteRoute: RepQuoteRoute,
  UploadBomRoute: UploadBomRoute,
  VersionsRoute: VersionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
